Catkin-ProjectName: rospkg
Version: 0.12.10
Depends: catkin, python-yaml
Description: Standalone Python library for the ROS package system.
Author: Ken Conley et al
Maintainer: Ken Conley <kwc@willowgarage.com>
Homepage: http://www.ros.org/wiki/rospkg

Catkin-CopyrightType: willowgarage
Catkin-DebRulesType: cmake

